import { writeFileSync } from "fs";
import resolveEnv from "../resolve-env";
import serialize from "serialize-javascript";

type CreateDeclaration = (_: {
  globalVariableName: string;
  envExampleFilePath: string;
  envFilePath: null | string;
  userEnvironment: boolean;
  outputFilePath: string;
}) => void;

const act: CreateDeclaration = ({
  globalVariableName,
  envExampleFilePath,
  envFilePath,
  userEnvironment,
  outputFilePath,
}) => {
  const env = resolveEnv({
    envExampleFilePath,
    envFilePath,
    userEnvironment,
  });

  const content = [
    "// Generated by '@runtime-env/cli'",
    "",
    `globalThis.${globalVariableName} = {`,
    ...Object.entries(env).map(
      ([key, value]) => `  "${key}": ${serialize(value)},`,
    ),
    "}",
    "",
  ].join("\n");

  writeFileSync(outputFilePath, content, "utf8");
};

export default act;
