// Generated by '@runtime-env/cli'

type Primitive = undefined | null | boolean | string | number;

type DeepReadonly<T> = T extends Primitive
  ? T
  : T extends Array<infer U>
    ? DeepReadonlyArray<U>
    : DeepReadonlyObject<T>;

type DeepReadonlyArray<T> = ReadonlyArray<DeepReadonly<T>>;

type DeepReadonlyObject<T> = {
  readonly [K in keyof T]: DeepReadonly<T[K]>;
};

declare global {
  var runtimeEnv: RuntimeEnv
}

export type RuntimeEnv = DeepReadonly<{
  FOO: string;
}>
