import { writeFileSync } from "fs";
import resolveEnvExampleKeys from "../resolve-env-example-keys";

type CreateDeclaration = (_: {
  globalVariableName: string;
  envExampleFilePath: string;
  outputFilePath: string;
}) => void;

const act: CreateDeclaration = ({
  globalVariableName,
  envExampleFilePath,
  outputFilePath,
}) => {
  const envExampleKeys = resolveEnvExampleKeys({ envExampleFilePath });

  const content = [
    "// Generated by '@runtime-env/cli'",
    "",
    `declare const ${globalVariableName}: {`,
    ...envExampleKeys.map((key) => `  readonly ${key}: string`),
    "}",
    "",
  ].join("\n");

  writeFileSync(outputFilePath, content, "utf8");
};

export default act;
