import { Command, program } from "commander";
import act from "./act";
import { writeFileSync } from "fs";

export default () => {
  return new Command("gen-ts")
    .description(
      "generate a TypeScript file that provides the corresponding type definitions for the JavaScript file generated by the gen-js command",
    )
    .option(
      "--output-file <outputFile>",
      "specify the output file to be written instead of being piped to stdout",
    )
    .action(async ({ outputFile }) => {
      const { globalVariableName, schemaFile, watch } = program.opts();

      await run();
      if (watch) {
        const chokidar = require("chokidar");
        chokidar.watch([schemaFile]).on("change", async () => {
          await run();
        });
      }

      async function run() {
        const { output } = await act({
          schemaFile,
          globalVariableName,
        });

        if (outputFile) {
          writeFileSync(outputFile, output, "utf8");
        } else {
          console.log(output);
        }
      }
    });
};
