import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import { tmpdir } from "tmp";

const schemaFile = path.resolve(__dirname, ".runtimeenvschema.json");

describe("integration - gen-ts", () => {
  test("globalVariableName", () => {
    const result = spawnSync(
      "node",
      ["../bin/runtime-env.js", "gen-ts", "--global-variable-name", "env"],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     type Primitive = undefined | null | boolean | string | number;

     type DeepReadonly<T> = T extends Primitive
       ? T
       : T extends Array<infer U>
         ? DeepReadonlyArray<U>
         : DeepReadonlyObject<T>;

     type DeepReadonlyArray<T> = ReadonlyArray<DeepReadonly<T>>;

     type DeepReadonlyObject<T> = {
       readonly [K in keyof T]: DeepReadonly<T[K]>;
     };

     declare global {
       var env: Env
     }

     export type Env = DeepReadonly<{
       FOO: string;
       BAR?: {
         BAZ?: string;
       };
     }>

     ",
       "",
     ]
    `);
  });

  test("schemaFile", () => {
    const result = spawnSync(
      "node",
      ["../bin/runtime-env.js", "gen-ts", "--schema-file", schemaFile],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     type Primitive = undefined | null | boolean | string | number;

     type DeepReadonly<T> = T extends Primitive
       ? T
       : T extends Array<infer U>
         ? DeepReadonlyArray<U>
         : DeepReadonlyObject<T>;

     type DeepReadonlyArray<T> = ReadonlyArray<DeepReadonly<T>>;

     type DeepReadonlyObject<T> = {
       readonly [K in keyof T]: DeepReadonly<T[K]>;
     };

     declare global {
       var runtimeEnv: RuntimeEnv
     }

     export type RuntimeEnv = DeepReadonly<{
       FOO: string;
       BAR?: {
         BAZ?: string;
       };
     }>

     ",
       "",
     ]
    `);
  });

  test("schemaFile - invalid", () => {
    const result = spawnSync(
      "node",
      ["../bin/runtime-env.js", "gen-ts", "--schema-file", "invalid"],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(1);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "",
       "[@runtime-env/cli]
       schema file not found: no such file, open 'invalid'
     ",
     ]
    `);
  });

  test("outputFile", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-ts",
        "--output-file",
        path.resolve(tmpdir, "runtime-env-gen-ts-output-file.ts"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "",
       "",
     ]
    `);
    expect(
      fs.readFileSync(
        path.resolve(tmpdir, "runtime-env-gen-ts-output-file.ts"),
        "utf8",
      ),
    ).toMatchInlineSnapshot(`
     "// Generated by '@runtime-env/cli'

     type Primitive = undefined | null | boolean | string | number;

     type DeepReadonly<T> = T extends Primitive
       ? T
       : T extends Array<infer U>
         ? DeepReadonlyArray<U>
         : DeepReadonlyObject<T>;

     type DeepReadonlyArray<T> = ReadonlyArray<DeepReadonly<T>>;

     type DeepReadonlyObject<T> = {
       readonly [K in keyof T]: DeepReadonly<T[K]>;
     };

     declare global {
       var runtimeEnv: RuntimeEnv
     }

     export type RuntimeEnv = DeepReadonly<{
       FOO: string;
       BAR?: {
         BAZ?: string;
       };
     }>
     "
    `);
  });

  test("prohibited default keyword", () => {
    const prohibitedSchemaFile = path.resolve(
      tmpdir,
      "prohibited-default-ts.json",
    );
    fs.writeFileSync(
      prohibitedSchemaFile,
      JSON.stringify({
        type: "object",
        properties: {
          FOO: {
            type: "string",
            default: "bar",
          },
        },
      }),
    );
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-ts",
        "--schema-file",
        prohibitedSchemaFile,
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(1);
    expect(result.output[2]).toContain(
      "schema is invalid: data/properties/FOO/default is prohibited",
    );
    fs.unlinkSync(prohibitedSchemaFile);
  });
});
