import fs from "fs";
import path from "path";
import { spawnSync } from "child_process";
import { tmpdir } from "tmp";

const schemaFile = path.resolve(__dirname, ".runtimeenvschema.json");
const requiredEnv = {
  FOO: "inline",
};
const requiredEnvInvalid = {};
const optionalEnv = {
  FOO: "inline",
  BAR: '{"BAZ":"baz"}',
};
const optionalEnvInvalid = {
  FOO: "inline",
  BAR: "invalid",
};

// write integration tests here for gen-js command
describe("integration - gen-js", () => {
  test("globalVariableName", () => {
    const result = spawnSync(
      "node",
      ["../bin/runtime-env.js", "gen-js", "--global-variable-name", "env"],
      {
        encoding: "utf8",
        stdio: "pipe",
        env: {
          ...process.env,
          ...requiredEnv,
        },
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.env = {
       "FOO": "inline",
       "BAR": undefined,
     }

     ",
       "",
     ]
    `);
  });

  test("schemaFile", () => {
    const result = spawnSync(
      "node",
      ["../bin/runtime-env.js", "gen-js", "--schema-file", schemaFile],
      {
        encoding: "utf8",
        stdio: "pipe",
        env: {
          ...process.env,
          ...requiredEnv,
        },
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "inline",
       "BAR": undefined,
     }

     ",
       "",
     ]
    `);
  });

  test("schemaFile - invalid", () => {
    const result = spawnSync(
      "node",
      ["../bin/runtime-env.js", "gen-js", "--schema-file", "invalid"],
      {
        encoding: "utf8",
        stdio: "pipe",
        env: {
          ...process.env,
          ...requiredEnv,
        },
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(1);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "",
       "[@runtime-env/cli]
       schema file not found: no such file, open 'invalid'
     ",
     ]
    `);
  });

  test("outputFile", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--output-file",
        path.resolve(tmpdir, "runtime-env-gen-js-output-file.js"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        env: {
          ...process.env,
          ...requiredEnv,
        },
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "",
       "",
     ]
    `);
    expect(
      fs.readFileSync(
        path.resolve(tmpdir, "runtime-env-gen-js-output-file.js"),
        "utf8",
      ),
    ).toMatchInlineSnapshot(`
     "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "inline",
       "BAR": undefined,
     }
     "
    `);
  });

  test("envFile - empty", () => {
    const result = spawnSync("node", ["../bin/runtime-env.js", "gen-js"], {
      encoding: "utf8",
      stdio: "pipe",
      env: {
        ...process.env,
        ...requiredEnv,
      },
      cwd: __dirname,
    });
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "inline",
       "BAR": undefined,
     }

     ",
       "",
     ]
    `);
  });

  test("envFile - required", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--env-file",
        path.resolve(__dirname, ".env.required"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "1",
       "BAR": undefined,
     }

     ",
       "",
     ]
    `);
  });

  test("envFile - optional", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--env-file",
        path.resolve(__dirname, ".env.optional"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "2",
       "BAR": {"BAZ":"2"},
     }

     ",
       "",
     ]
    `);
  });

  test("envFile - invalid", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--env-file",
        path.resolve(__dirname, ".env.invalid"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).not.toBe(0);
    expect(result.output[2]).toContain(".env.invalid");
    expect(result.output[2]).toContain("not found");
  });

  test("envFile - multiple + inline", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--env-file",
        path.resolve(__dirname, ".env.required"),
        "--env-file",
        path.resolve(__dirname, ".env.optional"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        env: {
          ...process.env,
          ...requiredEnv,
        },
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "inline",
       "BAR": {"BAZ":"2"},
     }

     ",
       "",
     ]
    `);
  });

  test("envFile - multiple", () => {
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--env-file",
        path.resolve(__dirname, ".env.required"),
        "--env-file",
        path.resolve(__dirname, ".env.optional"),
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "2",
       "BAR": {"BAZ":"2"},
     }

     ",
       "",
     ]
    `);
  });

  test("requiredEnv", () => {
    const result = spawnSync("node", ["../bin/runtime-env.js", "gen-js"], {
      encoding: "utf8",
      stdio: "pipe",
      env: {
        ...process.env,
        ...requiredEnv,
      },
      cwd: __dirname,
    });
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "inline",
       "BAR": undefined,
     }

     ",
       "",
     ]
    `);
  });

  test("requiredEnv - invalid", () => {
    const result = spawnSync("node", ["../bin/runtime-env.js", "gen-js"], {
      encoding: "utf8",
      stdio: "pipe",
      env: {
        ...process.env,
        ...requiredEnvInvalid,
      },
      cwd: __dirname,
    });
    expect(result.status).toBe(1);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "",
       "[@runtime-env/cli]
       env is invalid: [{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"FOO"},"message":"must have required property 'FOO'"}]
     ",
     ]
    `);
  });

  test("optionalEnv", () => {
    const result = spawnSync("node", ["../bin/runtime-env.js", "gen-js"], {
      encoding: "utf8",
      stdio: "pipe",
      env: {
        ...process.env,
        ...optionalEnv,
      },
      cwd: __dirname,
    });
    expect(result.status).toBe(0);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "// Generated by '@runtime-env/cli'

     globalThis.runtimeEnv = {
       "FOO": "inline",
       "BAR": {"BAZ":"baz"},
     }

     ",
       "",
     ]
    `);
  });

  test("optionalEnv - invalid", () => {
    const result = spawnSync("node", ["../bin/runtime-env.js", "gen-js"], {
      encoding: "utf8",
      stdio: "pipe",
      env: {
        ...process.env,
        ...optionalEnvInvalid,
      },
      cwd: __dirname,
    });
    expect(result.status).toBe(1);
    expect(result.output).toMatchInlineSnapshot(`
     [
       null,
       "",
       "[@runtime-env/cli]
       env is invalid: [{"instancePath":"/BAR","schemaPath":"#/properties/BAR/type","keyword":"type","params":{"type":"object"},"message":"must be object"}]
     ",
     ]
    `);
  });

  test("prohibited default keyword", () => {
    const prohibitedSchemaFile = path.resolve(
      tmpdir,
      "prohibited-default.json",
    );
    fs.writeFileSync(
      prohibitedSchemaFile,
      JSON.stringify({
        type: "object",
        properties: {
          FOO: {
            type: "string",
            default: "bar",
          },
        },
      }),
    );
    const result = spawnSync(
      "node",
      [
        "../bin/runtime-env.js",
        "gen-js",
        "--schema-file",
        prohibitedSchemaFile,
      ],
      {
        encoding: "utf8",
        stdio: "pipe",
        cwd: __dirname,
      },
    );
    expect(result.status).toBe(1);
    expect(result.output[2]).toContain(
      "schema is invalid: data/properties/FOO/default is prohibited",
    );
    fs.unlinkSync(prohibitedSchemaFile);
  });
});
